version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    restart: always
    volumes:
      - .:/opt/backend
    ports:
      - 8000:8000
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    restart: always
    volumes:
      - ./frontend:/opt/frontend
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    tty: true
    command: yarn start
    depends_on:
      - backend
