# Generated by Django 3.0.5 on 2020-04-29 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
                ('done', models.BooleanField(default=False, verbose_name='完了済み')),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
